package com.z.db.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.z.db.greendao.entities.Department;
import com.z.db.greendao.entities.ErrorLog;
import com.z.db.greendao.entities.User;

import com.z.db.greendao.dao.DepartmentDao;
import com.z.db.greendao.dao.ErrorLogDao;
import com.z.db.greendao.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig departmentDaoConfig;
    private final DaoConfig errorLogDaoConfig;
    private final DaoConfig userDaoConfig;

    private final DepartmentDao departmentDao;
    private final ErrorLogDao errorLogDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        departmentDaoConfig = daoConfigMap.get(DepartmentDao.class).clone();
        departmentDaoConfig.initIdentityScope(type);

        errorLogDaoConfig = daoConfigMap.get(ErrorLogDao.class).clone();
        errorLogDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        departmentDao = new DepartmentDao(departmentDaoConfig, this);
        errorLogDao = new ErrorLogDao(errorLogDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Department.class, departmentDao);
        registerDao(ErrorLog.class, errorLogDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        departmentDaoConfig.clearIdentityScope();
        errorLogDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public DepartmentDao getDepartmentDao() {
        return departmentDao;
    }

    public ErrorLogDao getErrorLogDao() {
        return errorLogDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
